---
- name: Install and configure Apache2
  hosts: serverweb
  become: true
  tasks:
    - name: Install Apache2
      apt:
        name: apache2
        state: present

- name: Install and configure Apache2
  hosts: serverweb
  become: true
  tasks:
    - name: Install Apache2
      apt:
        name: apache2
        state: present
    - name: Create custom index page
      copy:
        content:  <html>
          <head>
            <title>Bienvenue sur notre site web perso</title>
          </head>
          <body>
            <h1>Bienvenue sur le Site informatique</h1>
            <p>Nous espérons que vous apprécierez votre visite.</p>
          </body>
          </html>
        dest: /var/www/html/index.html
    - name: Start Apache2 service
      service:
        name: apache2
        state: started
